/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : string,
  'activityType' : ActivityType,
  'groupId' : string,
  'timestamp' : Time,
  'details' : string,
}
export type ActivityType = { 'expenseAdded' : null } |
  { 'memberJoined' : null } |
  { 'milestoneUpdated' : null } |
  { 'contributionMade' : null };
export interface Contribution {
  'id' : string,
  'member' : Principal,
  'status' : ContributionStatus,
  'groupId' : string,
  'amount' : bigint,
  'datePaid' : [] | [Time],
}
export type ContributionCycle = { 'quarterly' : null } |
  { 'monthly' : null } |
  { 'weekly' : null };
export type ContributionStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'overdue' : null };
export interface ContributionWithProfile {
  'id' : string,
  'contributorName' : string,
  'member' : Principal,
  'status' : ContributionStatus,
  'groupId' : string,
  'amount' : bigint,
  'datePaid' : [] | [Time],
}
export interface CropTemplate {
  'name' : string,
  'category' : string,
  'defaultMilestones' : Array<DefaultMilestone>,
}
export interface DefaultMilestone {
  'name' : string,
  'daysOffset' : bigint,
  'description' : string,
}
export interface Expense {
  'id' : string,
  'receiptImage' : [] | [ExternalBlob],
  'description' : string,
  'dateSpent' : Time,
  'groupId' : string,
  'addedBy' : Principal,
  'category' : string,
  'amount' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface FinancialSummary {
  'totalRaised' : bigint,
  'totalSpent' : bigint,
  'remainingBalance' : bigint,
  'currency' : string,
  'totalRevenue' : bigint,
  'netProfit' : bigint,
}
export interface GroupDashboardData {
  'activityFeed' : Array<Activity>,
  'recentContributions' : Array<ContributionWithProfile>,
  'groupId' : string,
  'groupProgress' : GroupProgress,
  'groupInfo' : VentureGroup,
  'financialSummary' : FinancialSummary,
  'milestones' : Array<Milestone>,
}
export interface GroupMember {
  'principal' : Principal,
  'role' : UserRole,
  'joinedDate' : Time,
}
export interface GroupProgress {
  'progressPercentage' : bigint,
  'totalContributions' : bigint,
  'groupId' : string,
  'totalSpent' : bigint,
  'targetAmount' : bigint,
  'remainingBalance' : bigint,
  'currency' : string,
  'totalRevenue' : bigint,
  'perMemberContribution' : bigint,
  'netProfit' : bigint,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface Milestone {
  'id' : string,
  'status' : MilestoneStatus,
  'name' : string,
  'description' : string,
  'groupId' : string,
  'targetDate' : Time,
  'image' : [] | [ExternalBlob],
}
export type MilestoneStatus = { 'pending' : null } |
  { 'completed' : null };
export interface OwnershipPercentage {
  'totalContributed' : bigint,
  'memberPrincipal' : Principal,
  'ownershipPercentage' : bigint,
}
export interface Payout {
  'id' : string,
  'member' : Principal,
  'groupId' : string,
  'markedBy' : Principal,
  'amount' : bigint,
  'datePaid' : Time,
}
export interface PayoutSuggestion {
  'memberPrincipal' : Principal,
  'isPaid' : boolean,
  'memberName' : string,
  'ownershipPercentage' : bigint,
  'payoutAmount' : bigint,
}
export interface PlannedPayment {
  'id' : string,
  'member' : Principal,
  'status' : PlannedPaymentStatus,
  'dueDate' : Time,
  'description' : string,
  'groupId' : string,
  'amount' : bigint,
}
export type PlannedPaymentStatus = { 'upcoming' : null } |
  { 'paid' : null } |
  { 'missed' : null };
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface Revenue {
  'id' : string,
  'source' : string,
  'date' : Time,
  'description' : string,
  'groupId' : string,
  'addedBy' : Principal,
  'amount' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'created' : Time,
  'country' : string,
  'name' : string,
  'role' : UserRole,
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VentureGroup {
  'id' : string,
  'members' : Array<GroupMember>,
  'admin' : Principal,
  'endDate' : Time,
  'name' : string,
  'description' : string,
  'contributionCycle' : ContributionCycle,
  'targetAmount' : bigint,
  'currency' : string,
  'category' : string,
  'monthlyContributionAmount' : bigint,
  'startDate' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addActivity' : ActorMethod<[Activity], undefined>,
  'addContribution' : ActorMethod<[Contribution], undefined>,
  'addExpense' : ActorMethod<[Expense], undefined>,
  'addMilestone' : ActorMethod<[Milestone], undefined>,
  'addRevenue' : ActorMethod<[string, Revenue], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateOwnershipPercentages' : ActorMethod<
    [string],
    Array<OwnershipPercentage>
  >,
  'calculatePayouts' : ActorMethod<[string], Array<PayoutSuggestion>>,
  'createPlannedPayment' : ActorMethod<[PlannedPayment], undefined>,
  'createVentureGroupWithMilestones' : ActorMethod<
    [VentureGroup, string],
    undefined
  >,
  'deleteContribution' : ActorMethod<[string], undefined>,
  'deleteExpense' : ActorMethod<[string], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getActivityFeedByGroup' : ActorMethod<[string], Array<Activity>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getAllVentureGroups' : ActorMethod<[], Array<VentureGroup>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContributionsByGroup' : ActorMethod<[string], Array<Contribution>>,
  'getContributionsWithProfilesByGroup' : ActorMethod<
    [string],
    Array<ContributionWithProfile>
  >,
  'getCropTemplates' : ActorMethod<[], Array<CropTemplate>>,
  'getExpensesByGroup' : ActorMethod<[string], Array<Expense>>,
  'getFinancialSummaryByGroup' : ActorMethod<[string], FinancialSummary>,
  'getGroupDashboardData' : ActorMethod<[string], GroupDashboardData>,
  'getGroupProgress' : ActorMethod<[string], [] | [GroupProgress]>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getMilestonesByGroup' : ActorMethod<[string], Array<Milestone>>,
  'getMyPlannedPayments' : ActorMethod<[], Array<PlannedPayment>>,
  'getMyReturns' : ActorMethod<
    [string],
    {
      'totalReceived' : bigint,
      'totalContributed' : bigint,
      'netProfit' : bigint,
    }
  >,
  'getMyVentureGroups' : ActorMethod<[], Array<string>>,
  'getPayoutsByGroup' : ActorMethod<[string], Array<Payout>>,
  'getPlannedPaymentsByGroup' : ActorMethod<[string], Array<PlannedPayment>>,
  'getRevenuesByGroup' : ActorMethod<[string], Array<Revenue>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVentureGroup' : ActorMethod<[string], [] | [VentureGroup]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinVentureGroup' : ActorMethod<
    [string],
    {
      'userGroups' : Array<string>,
      'wasNewMember' : boolean,
      'group' : [] | [VentureGroup],
    }
  >,
  'recordPayout' : ActorMethod<[string, Principal, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'updateContribution' : ActorMethod<[string, Contribution], undefined>,
  'updateMilestoneStatus' : ActorMethod<[string, MilestoneStatus], undefined>,
  'updatePlannedPayment' : ActorMethod<[string, PlannedPayment], undefined>,
  'updateVentureGroup' : ActorMethod<[string, VentureGroup], undefined>,
  'uploadMilestoneImage' : ActorMethod<[string, ExternalBlob], undefined>,
  'uploadReceiptImage' : ActorMethod<[string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];