/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ActivityType = IDL.Variant({
  'expenseAdded' : IDL.Null,
  'memberJoined' : IDL.Null,
  'milestoneUpdated' : IDL.Null,
  'contributionMade' : IDL.Null,
});
export const Time = IDL.Int;
export const Activity = IDL.Record({
  'id' : IDL.Text,
  'activityType' : ActivityType,
  'groupId' : IDL.Text,
  'timestamp' : Time,
  'details' : IDL.Text,
});
export const ContributionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'overdue' : IDL.Null,
});
export const Contribution = IDL.Record({
  'id' : IDL.Text,
  'member' : IDL.Principal,
  'status' : ContributionStatus,
  'groupId' : IDL.Text,
  'amount' : IDL.Int,
  'datePaid' : IDL.Opt(Time),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Expense = IDL.Record({
  'id' : IDL.Text,
  'receiptImage' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
  'dateSpent' : Time,
  'groupId' : IDL.Text,
  'addedBy' : IDL.Principal,
  'category' : IDL.Text,
  'amount' : IDL.Int,
});
export const MilestoneStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const Milestone = IDL.Record({
  'id' : IDL.Text,
  'status' : MilestoneStatus,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'groupId' : IDL.Text,
  'targetDate' : Time,
  'image' : IDL.Opt(ExternalBlob),
});
export const Revenue = IDL.Record({
  'id' : IDL.Text,
  'source' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'groupId' : IDL.Text,
  'addedBy' : IDL.Principal,
  'amount' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OwnershipPercentage = IDL.Record({
  'totalContributed' : IDL.Int,
  'memberPrincipal' : IDL.Principal,
  'ownershipPercentage' : IDL.Int,
});
export const PayoutSuggestion = IDL.Record({
  'memberPrincipal' : IDL.Principal,
  'isPaid' : IDL.Bool,
  'memberName' : IDL.Text,
  'ownershipPercentage' : IDL.Int,
  'payoutAmount' : IDL.Int,
});
export const PlannedPaymentStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'paid' : IDL.Null,
  'missed' : IDL.Null,
});
export const PlannedPayment = IDL.Record({
  'id' : IDL.Text,
  'member' : IDL.Principal,
  'status' : PlannedPaymentStatus,
  'dueDate' : Time,
  'description' : IDL.Text,
  'groupId' : IDL.Text,
  'amount' : IDL.Int,
});
export const GroupMember = IDL.Record({
  'principal' : IDL.Principal,
  'role' : UserRole,
  'joinedDate' : Time,
});
export const ContributionCycle = IDL.Variant({
  'quarterly' : IDL.Null,
  'monthly' : IDL.Null,
  'weekly' : IDL.Null,
});
export const VentureGroup = IDL.Record({
  'id' : IDL.Text,
  'members' : IDL.Vec(GroupMember),
  'admin' : IDL.Principal,
  'endDate' : Time,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'contributionCycle' : ContributionCycle,
  'targetAmount' : IDL.Int,
  'currency' : IDL.Text,
  'category' : IDL.Text,
  'monthlyContributionAmount' : IDL.Int,
  'startDate' : Time,
});
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'created' : Time,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'role' : UserRole,
  'phone' : IDL.Opt(IDL.Text),
});
export const ContributionWithProfile = IDL.Record({
  'id' : IDL.Text,
  'contributorName' : IDL.Text,
  'member' : IDL.Principal,
  'status' : ContributionStatus,
  'groupId' : IDL.Text,
  'amount' : IDL.Int,
  'datePaid' : IDL.Opt(Time),
});
export const DefaultMilestone = IDL.Record({
  'name' : IDL.Text,
  'daysOffset' : IDL.Int,
  'description' : IDL.Text,
});
export const CropTemplate = IDL.Record({
  'name' : IDL.Text,
  'category' : IDL.Text,
  'defaultMilestones' : IDL.Vec(DefaultMilestone),
});
export const FinancialSummary = IDL.Record({
  'totalRaised' : IDL.Int,
  'totalSpent' : IDL.Int,
  'remainingBalance' : IDL.Int,
  'currency' : IDL.Text,
  'totalRevenue' : IDL.Int,
  'netProfit' : IDL.Int,
});
export const GroupProgress = IDL.Record({
  'progressPercentage' : IDL.Int,
  'totalContributions' : IDL.Int,
  'groupId' : IDL.Text,
  'totalSpent' : IDL.Int,
  'targetAmount' : IDL.Int,
  'remainingBalance' : IDL.Int,
  'currency' : IDL.Text,
  'totalRevenue' : IDL.Int,
  'perMemberContribution' : IDL.Int,
  'netProfit' : IDL.Int,
});
export const GroupDashboardData = IDL.Record({
  'activityFeed' : IDL.Vec(Activity),
  'recentContributions' : IDL.Vec(ContributionWithProfile),
  'groupId' : IDL.Text,
  'groupProgress' : GroupProgress,
  'groupInfo' : VentureGroup,
  'financialSummary' : FinancialSummary,
  'milestones' : IDL.Vec(Milestone),
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const Payout = IDL.Record({
  'id' : IDL.Text,
  'member' : IDL.Principal,
  'groupId' : IDL.Text,
  'markedBy' : IDL.Principal,
  'amount' : IDL.Int,
  'datePaid' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addActivity' : IDL.Func([Activity], [], []),
  'addContribution' : IDL.Func([Contribution], [], []),
  'addExpense' : IDL.Func([Expense], [], []),
  'addMilestone' : IDL.Func([Milestone], [], []),
  'addRevenue' : IDL.Func([IDL.Text, Revenue], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateOwnershipPercentages' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(OwnershipPercentage)],
      ['query'],
    ),
  'calculatePayouts' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PayoutSuggestion)],
      ['query'],
    ),
  'createPlannedPayment' : IDL.Func([PlannedPayment], [], []),
  'createVentureGroupWithMilestones' : IDL.Func(
      [VentureGroup, IDL.Text],
      [],
      [],
    ),
  'deleteContribution' : IDL.Func([IDL.Text], [], []),
  'deleteExpense' : IDL.Func([IDL.Text], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getActivityFeedByGroup' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Activity)],
      ['query'],
    ),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getAllVentureGroups' : IDL.Func([], [IDL.Vec(VentureGroup)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContributionsByGroup' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Contribution)],
      ['query'],
    ),
  'getContributionsWithProfilesByGroup' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContributionWithProfile)],
      ['query'],
    ),
  'getCropTemplates' : IDL.Func([], [IDL.Vec(CropTemplate)], ['query']),
  'getExpensesByGroup' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
  'getFinancialSummaryByGroup' : IDL.Func(
      [IDL.Text],
      [FinancialSummary],
      ['query'],
    ),
  'getGroupDashboardData' : IDL.Func(
      [IDL.Text],
      [GroupDashboardData],
      ['query'],
    ),
  'getGroupProgress' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(GroupProgress)],
      ['query'],
    ),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getMilestonesByGroup' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Milestone)],
      ['query'],
    ),
  'getMyPlannedPayments' : IDL.Func([], [IDL.Vec(PlannedPayment)], ['query']),
  'getMyReturns' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'totalReceived' : IDL.Int,
          'totalContributed' : IDL.Int,
          'netProfit' : IDL.Int,
        }),
      ],
      ['query'],
    ),
  'getMyVentureGroups' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getPayoutsByGroup' : IDL.Func([IDL.Text], [IDL.Vec(Payout)], ['query']),
  'getPlannedPaymentsByGroup' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PlannedPayment)],
      ['query'],
    ),
  'getRevenuesByGroup' : IDL.Func([IDL.Text], [IDL.Vec(Revenue)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVentureGroup' : IDL.Func([IDL.Text], [IDL.Opt(VentureGroup)], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinVentureGroup' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'userGroups' : IDL.Vec(IDL.Text),
          'wasNewMember' : IDL.Bool,
          'group' : IDL.Opt(VentureGroup),
        }),
      ],
      [],
    ),
  'recordPayout' : IDL.Func([IDL.Text, IDL.Principal, IDL.Int], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'updateContribution' : IDL.Func([IDL.Text, Contribution], [], []),
  'updateMilestoneStatus' : IDL.Func([IDL.Text, MilestoneStatus], [], []),
  'updatePlannedPayment' : IDL.Func([IDL.Text, PlannedPayment], [], []),
  'updateVentureGroup' : IDL.Func([IDL.Text, VentureGroup], [], []),
  'uploadMilestoneImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'uploadReceiptImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ActivityType = IDL.Variant({
    'expenseAdded' : IDL.Null,
    'memberJoined' : IDL.Null,
    'milestoneUpdated' : IDL.Null,
    'contributionMade' : IDL.Null,
  });
  const Time = IDL.Int;
  const Activity = IDL.Record({
    'id' : IDL.Text,
    'activityType' : ActivityType,
    'groupId' : IDL.Text,
    'timestamp' : Time,
    'details' : IDL.Text,
  });
  const ContributionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'overdue' : IDL.Null,
  });
  const Contribution = IDL.Record({
    'id' : IDL.Text,
    'member' : IDL.Principal,
    'status' : ContributionStatus,
    'groupId' : IDL.Text,
    'amount' : IDL.Int,
    'datePaid' : IDL.Opt(Time),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Expense = IDL.Record({
    'id' : IDL.Text,
    'receiptImage' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
    'dateSpent' : Time,
    'groupId' : IDL.Text,
    'addedBy' : IDL.Principal,
    'category' : IDL.Text,
    'amount' : IDL.Int,
  });
  const MilestoneStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Milestone = IDL.Record({
    'id' : IDL.Text,
    'status' : MilestoneStatus,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'groupId' : IDL.Text,
    'targetDate' : Time,
    'image' : IDL.Opt(ExternalBlob),
  });
  const Revenue = IDL.Record({
    'id' : IDL.Text,
    'source' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'groupId' : IDL.Text,
    'addedBy' : IDL.Principal,
    'amount' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OwnershipPercentage = IDL.Record({
    'totalContributed' : IDL.Int,
    'memberPrincipal' : IDL.Principal,
    'ownershipPercentage' : IDL.Int,
  });
  const PayoutSuggestion = IDL.Record({
    'memberPrincipal' : IDL.Principal,
    'isPaid' : IDL.Bool,
    'memberName' : IDL.Text,
    'ownershipPercentage' : IDL.Int,
    'payoutAmount' : IDL.Int,
  });
  const PlannedPaymentStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'paid' : IDL.Null,
    'missed' : IDL.Null,
  });
  const PlannedPayment = IDL.Record({
    'id' : IDL.Text,
    'member' : IDL.Principal,
    'status' : PlannedPaymentStatus,
    'dueDate' : Time,
    'description' : IDL.Text,
    'groupId' : IDL.Text,
    'amount' : IDL.Int,
  });
  const GroupMember = IDL.Record({
    'principal' : IDL.Principal,
    'role' : UserRole,
    'joinedDate' : Time,
  });
  const ContributionCycle = IDL.Variant({
    'quarterly' : IDL.Null,
    'monthly' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const VentureGroup = IDL.Record({
    'id' : IDL.Text,
    'members' : IDL.Vec(GroupMember),
    'admin' : IDL.Principal,
    'endDate' : Time,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'contributionCycle' : ContributionCycle,
    'targetAmount' : IDL.Int,
    'currency' : IDL.Text,
    'category' : IDL.Text,
    'monthlyContributionAmount' : IDL.Int,
    'startDate' : Time,
  });
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'created' : Time,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'role' : UserRole,
    'phone' : IDL.Opt(IDL.Text),
  });
  const ContributionWithProfile = IDL.Record({
    'id' : IDL.Text,
    'contributorName' : IDL.Text,
    'member' : IDL.Principal,
    'status' : ContributionStatus,
    'groupId' : IDL.Text,
    'amount' : IDL.Int,
    'datePaid' : IDL.Opt(Time),
  });
  const DefaultMilestone = IDL.Record({
    'name' : IDL.Text,
    'daysOffset' : IDL.Int,
    'description' : IDL.Text,
  });
  const CropTemplate = IDL.Record({
    'name' : IDL.Text,
    'category' : IDL.Text,
    'defaultMilestones' : IDL.Vec(DefaultMilestone),
  });
  const FinancialSummary = IDL.Record({
    'totalRaised' : IDL.Int,
    'totalSpent' : IDL.Int,
    'remainingBalance' : IDL.Int,
    'currency' : IDL.Text,
    'totalRevenue' : IDL.Int,
    'netProfit' : IDL.Int,
  });
  const GroupProgress = IDL.Record({
    'progressPercentage' : IDL.Int,
    'totalContributions' : IDL.Int,
    'groupId' : IDL.Text,
    'totalSpent' : IDL.Int,
    'targetAmount' : IDL.Int,
    'remainingBalance' : IDL.Int,
    'currency' : IDL.Text,
    'totalRevenue' : IDL.Int,
    'perMemberContribution' : IDL.Int,
    'netProfit' : IDL.Int,
  });
  const GroupDashboardData = IDL.Record({
    'activityFeed' : IDL.Vec(Activity),
    'recentContributions' : IDL.Vec(ContributionWithProfile),
    'groupId' : IDL.Text,
    'groupProgress' : GroupProgress,
    'groupInfo' : VentureGroup,
    'financialSummary' : FinancialSummary,
    'milestones' : IDL.Vec(Milestone),
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const Payout = IDL.Record({
    'id' : IDL.Text,
    'member' : IDL.Principal,
    'groupId' : IDL.Text,
    'markedBy' : IDL.Principal,
    'amount' : IDL.Int,
    'datePaid' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addActivity' : IDL.Func([Activity], [], []),
    'addContribution' : IDL.Func([Contribution], [], []),
    'addExpense' : IDL.Func([Expense], [], []),
    'addMilestone' : IDL.Func([Milestone], [], []),
    'addRevenue' : IDL.Func([IDL.Text, Revenue], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateOwnershipPercentages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(OwnershipPercentage)],
        ['query'],
      ),
    'calculatePayouts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PayoutSuggestion)],
        ['query'],
      ),
    'createPlannedPayment' : IDL.Func([PlannedPayment], [], []),
    'createVentureGroupWithMilestones' : IDL.Func(
        [VentureGroup, IDL.Text],
        [],
        [],
      ),
    'deleteContribution' : IDL.Func([IDL.Text], [], []),
    'deleteExpense' : IDL.Func([IDL.Text], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getActivityFeedByGroup' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getAllVentureGroups' : IDL.Func([], [IDL.Vec(VentureGroup)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContributionsByGroup' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Contribution)],
        ['query'],
      ),
    'getContributionsWithProfilesByGroup' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContributionWithProfile)],
        ['query'],
      ),
    'getCropTemplates' : IDL.Func([], [IDL.Vec(CropTemplate)], ['query']),
    'getExpensesByGroup' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
    'getFinancialSummaryByGroup' : IDL.Func(
        [IDL.Text],
        [FinancialSummary],
        ['query'],
      ),
    'getGroupDashboardData' : IDL.Func(
        [IDL.Text],
        [GroupDashboardData],
        ['query'],
      ),
    'getGroupProgress' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GroupProgress)],
        ['query'],
      ),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getMilestonesByGroup' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Milestone)],
        ['query'],
      ),
    'getMyPlannedPayments' : IDL.Func([], [IDL.Vec(PlannedPayment)], ['query']),
    'getMyReturns' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'totalReceived' : IDL.Int,
            'totalContributed' : IDL.Int,
            'netProfit' : IDL.Int,
          }),
        ],
        ['query'],
      ),
    'getMyVentureGroups' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getPayoutsByGroup' : IDL.Func([IDL.Text], [IDL.Vec(Payout)], ['query']),
    'getPlannedPaymentsByGroup' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PlannedPayment)],
        ['query'],
      ),
    'getRevenuesByGroup' : IDL.Func([IDL.Text], [IDL.Vec(Revenue)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVentureGroup' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VentureGroup)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinVentureGroup' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'userGroups' : IDL.Vec(IDL.Text),
            'wasNewMember' : IDL.Bool,
            'group' : IDL.Opt(VentureGroup),
          }),
        ],
        [],
      ),
    'recordPayout' : IDL.Func([IDL.Text, IDL.Principal, IDL.Int], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'updateContribution' : IDL.Func([IDL.Text, Contribution], [], []),
    'updateMilestoneStatus' : IDL.Func([IDL.Text, MilestoneStatus], [], []),
    'updatePlannedPayment' : IDL.Func([IDL.Text, PlannedPayment], [], []),
    'updateVentureGroup' : IDL.Func([IDL.Text, VentureGroup], [], []),
    'uploadMilestoneImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'uploadReceiptImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };