/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface PayoutSuggestion {
    memberPrincipal: Principal;
    isPaid: boolean;
    memberName: string;
    ownershipPercentage: bigint;
    payoutAmount: bigint;
}
export interface Payout {
    id: string;
    member: Principal;
    groupId: string;
    markedBy: Principal;
    amount: bigint;
    datePaid: Time;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface DefaultMilestone {
    name: string;
    daysOffset: bigint;
    description: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface InviteCode {
    created: Time;
    code: string;
    used: boolean;
}
export interface GroupDashboardData {
    activityFeed: Array<Activity>;
    recentContributions: Array<ContributionWithProfile>;
    groupId: string;
    groupProgress: GroupProgress;
    groupInfo: VentureGroup;
    financialSummary: FinancialSummary;
    milestones: Array<Milestone>;
}
export interface Contribution {
    id: string;
    member: Principal;
    status: ContributionStatus;
    groupId: string;
    amount: bigint;
    datePaid?: Time;
}
export interface OwnershipPercentage {
    totalContributed: bigint;
    memberPrincipal: Principal;
    ownershipPercentage: bigint;
}
export interface FinancialSummary {
    totalRaised: bigint;
    totalSpent: bigint;
    remainingBalance: bigint;
    currency: string;
    totalRevenue: bigint;
    netProfit: bigint;
}
export interface GroupMember {
    principal: Principal;
    role: UserRole;
    joinedDate: Time;
}
export interface Revenue {
    id: string;
    source: string;
    date: Time;
    description: string;
    groupId: string;
    addedBy: Principal;
    amount: bigint;
}
export interface Expense {
    id: string;
    receiptImage?: ExternalBlob;
    description: string;
    dateSpent: Time;
    groupId: string;
    addedBy: Principal;
    category: string;
    amount: bigint;
}
export interface Milestone {
    id: string;
    status: MilestoneStatus;
    name: string;
    description: string;
    groupId: string;
    targetDate: Time;
    image?: ExternalBlob;
}
export interface RSVP {
    name: string;
    inviteCode: string;
    timestamp: Time;
    attending: boolean;
}
export interface GroupProgress {
    progressPercentage: bigint;
    totalContributions: bigint;
    groupId: string;
    totalSpent: bigint;
    targetAmount: bigint;
    remainingBalance: bigint;
    currency: string;
    totalRevenue: bigint;
    perMemberContribution: bigint;
    netProfit: bigint;
}
export interface Activity {
    id: string;
    activityType: ActivityType;
    groupId: string;
    timestamp: Time;
    details: string;
}
export interface PlannedPayment {
    id: string;
    member: Principal;
    status: PlannedPaymentStatus;
    dueDate: Time;
    description: string;
    groupId: string;
    amount: bigint;
}
export interface CropTemplate {
    name: string;
    category: string;
    defaultMilestones: Array<DefaultMilestone>;
}
export interface ContributionWithProfile {
    id: string;
    contributorName: string;
    member: Principal;
    status: ContributionStatus;
    groupId: string;
    amount: bigint;
    datePaid?: Time;
}
export interface VentureGroup {
    id: string;
    members: Array<GroupMember>;
    admin: Principal;
    endDate: Time;
    name: string;
    description: string;
    contributionCycle: ContributionCycle;
    targetAmount: bigint;
    currency: string;
    category: string;
    monthlyContributionAmount: bigint;
    startDate: Time;
}
export interface UserProfile {
    created: Time;
    country: string;
    name: string;
    role: UserRole;
    phone?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ActivityType {
    expenseAdded = "expenseAdded",
    memberJoined = "memberJoined",
    milestoneUpdated = "milestoneUpdated",
    contributionMade = "contributionMade"
}
export enum ContributionCycle {
    quarterly = "quarterly",
    monthly = "monthly",
    weekly = "weekly"
}
export enum ContributionStatus {
    pending = "pending",
    paid = "paid",
    overdue = "overdue"
}
export enum MilestoneStatus {
    pending = "pending",
    completed = "completed"
}
export enum PlannedPaymentStatus {
    upcoming = "upcoming",
    paid = "paid",
    missed = "missed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addActivity(activity: Activity): Promise<void>;
    addContribution(contribution: Contribution): Promise<void>;
    addExpense(expense: Expense): Promise<void>;
    addMilestone(milestone: Milestone): Promise<void>;
    addRevenue(groupId: string, revenue: Revenue): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateOwnershipPercentages(groupId: string): Promise<Array<OwnershipPercentage>>;
    calculatePayouts(groupId: string): Promise<Array<PayoutSuggestion>>;
    createPlannedPayment(payment: PlannedPayment): Promise<void>;
    createVentureGroupWithMilestones(group: VentureGroup, cropType: string): Promise<void>;
    deleteContribution(contributionId: string): Promise<void>;
    deleteExpense(expenseId: string): Promise<void>;
    generateInviteCode(): Promise<string>;
    getActivityFeedByGroup(groupId: string): Promise<Array<Activity>>;
    getAllRSVPs(): Promise<Array<RSVP>>;
    getAllVentureGroups(): Promise<Array<VentureGroup>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContributionsByGroup(groupId: string): Promise<Array<Contribution>>;
    getContributionsWithProfilesByGroup(groupId: string): Promise<Array<ContributionWithProfile>>;
    getCropTemplates(): Promise<Array<CropTemplate>>;
    getExpensesByGroup(groupId: string): Promise<Array<Expense>>;
    getFinancialSummaryByGroup(groupId: string): Promise<FinancialSummary>;
    getGroupDashboardData(groupId: string): Promise<GroupDashboardData>;
    getGroupProgress(groupId: string): Promise<GroupProgress | null>;
    getInviteCodes(): Promise<Array<InviteCode>>;
    getMilestonesByGroup(groupId: string): Promise<Array<Milestone>>;
    getMyPlannedPayments(): Promise<Array<PlannedPayment>>;
    getMyReturns(groupId: string): Promise<{
        totalReceived: bigint;
        totalContributed: bigint;
        netProfit: bigint;
    }>;
    getMyVentureGroups(): Promise<Array<string>>;
    getPayoutsByGroup(groupId: string): Promise<Array<Payout>>;
    getPlannedPaymentsByGroup(groupId: string): Promise<Array<PlannedPayment>>;
    getRevenuesByGroup(groupId: string): Promise<Array<Revenue>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVentureGroup(id: string): Promise<VentureGroup | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    joinVentureGroup(groupId: string): Promise<{
        userGroups: Array<string>;
        wasNewMember: boolean;
        group?: VentureGroup;
    }>;
    recordPayout(groupId: string, member: Principal, amount: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitRSVP(name: string, attending: boolean, inviteCode: string): Promise<void>;
    updateContribution(contributionId: string, updatedContribution: Contribution): Promise<void>;
    updateMilestoneStatus(milestoneId: string, status: MilestoneStatus): Promise<void>;
    updatePlannedPayment(paymentId: string, updatedPayment: PlannedPayment): Promise<void>;
    updateVentureGroup(groupId: string, updatedGroup: VentureGroup): Promise<void>;
    uploadMilestoneImage(milestoneId: string, blob: ExternalBlob): Promise<void>;
    uploadReceiptImage(expenseId: string, blob: ExternalBlob): Promise<void>;
}
import type { Activity as _Activity, ActivityType as _ActivityType, Contribution as _Contribution, ContributionCycle as _ContributionCycle, ContributionStatus as _ContributionStatus, ContributionWithProfile as _ContributionWithProfile, Expense as _Expense, ExternalBlob as _ExternalBlob, FinancialSummary as _FinancialSummary, GroupDashboardData as _GroupDashboardData, GroupMember as _GroupMember, GroupProgress as _GroupProgress, Milestone as _Milestone, MilestoneStatus as _MilestoneStatus, PlannedPayment as _PlannedPayment, PlannedPaymentStatus as _PlannedPaymentStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, VentureGroup as _VentureGroup, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addActivity(arg0: Activity): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addActivity(to_candid_Activity_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addActivity(to_candid_Activity_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addContribution(arg0: Contribution): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addContribution(to_candid_Contribution_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContribution(to_candid_Contribution_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addExpense(arg0: Expense): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(await to_candid_Expense_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(await to_candid_Expense_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMilestone(arg0: Milestone): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMilestone(await to_candid_Milestone_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMilestone(await to_candid_Milestone_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addRevenue(arg0: string, arg1: Revenue): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRevenue(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRevenue(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n23(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n23(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateOwnershipPercentages(arg0: string): Promise<Array<OwnershipPercentage>> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateOwnershipPercentages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateOwnershipPercentages(arg0);
            return result;
        }
    }
    async calculatePayouts(arg0: string): Promise<Array<PayoutSuggestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.calculatePayouts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculatePayouts(arg0);
            return result;
        }
    }
    async createPlannedPayment(arg0: PlannedPayment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlannedPayment(to_candid_PlannedPayment_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlannedPayment(to_candid_PlannedPayment_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createVentureGroupWithMilestones(arg0: VentureGroup, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createVentureGroupWithMilestones(to_candid_VentureGroup_n29(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVentureGroupWithMilestones(to_candid_VentureGroup_n29(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async deleteContribution(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContribution(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContribution(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async generateInviteCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteCode();
            return result;
        }
    }
    async getActivityFeedByGroup(arg0: string): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityFeedByGroup(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityFeedByGroup(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRSVPs(): Promise<Array<RSVP>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRSVPs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRSVPs();
            return result;
        }
    }
    async getAllVentureGroups(): Promise<Array<VentureGroup>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVentureGroups();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVentureGroups();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContributionsByGroup(arg0: string): Promise<Array<Contribution>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContributionsByGroup(arg0);
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContributionsByGroup(arg0);
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContributionsWithProfilesByGroup(arg0: string): Promise<Array<ContributionWithProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContributionsWithProfilesByGroup(arg0);
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContributionsWithProfilesByGroup(arg0);
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCropTemplates(): Promise<Array<CropTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCropTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCropTemplates();
            return result;
        }
    }
    async getExpensesByGroup(arg0: string): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesByGroup(arg0);
                return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesByGroup(arg0);
            return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFinancialSummaryByGroup(arg0: string): Promise<FinancialSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialSummaryByGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialSummaryByGroup(arg0);
            return result;
        }
    }
    async getGroupDashboardData(arg0: string): Promise<GroupDashboardData> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupDashboardData(arg0);
                return from_candid_GroupDashboardData_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupDashboardData(arg0);
            return from_candid_GroupDashboardData_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroupProgress(arg0: string): Promise<GroupProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupProgress(arg0);
                return from_candid_opt_n76(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupProgress(arg0);
            return from_candid_opt_n76(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInviteCodes(): Promise<Array<InviteCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteCodes();
            return result;
        }
    }
    async getMilestonesByGroup(arg0: string): Promise<Array<Milestone>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMilestonesByGroup(arg0);
                return from_candid_vec_n71(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMilestonesByGroup(arg0);
            return from_candid_vec_n71(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPlannedPayments(): Promise<Array<PlannedPayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPlannedPayments();
                return from_candid_vec_n77(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPlannedPayments();
            return from_candid_vec_n77(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyReturns(arg0: string): Promise<{
        totalReceived: bigint;
        totalContributed: bigint;
        netProfit: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyReturns(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyReturns(arg0);
            return result;
        }
    }
    async getMyVentureGroups(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyVentureGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyVentureGroups();
            return result;
        }
    }
    async getPayoutsByGroup(arg0: string): Promise<Array<Payout>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayoutsByGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayoutsByGroup(arg0);
            return result;
        }
    }
    async getPlannedPaymentsByGroup(arg0: string): Promise<Array<PlannedPayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlannedPaymentsByGroup(arg0);
                return from_candid_vec_n77(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlannedPaymentsByGroup(arg0);
            return from_candid_vec_n77(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRevenuesByGroup(arg0: string): Promise<Array<Revenue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenuesByGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenuesByGroup(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVentureGroup(arg0: string): Promise<VentureGroup | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVentureGroup(arg0);
                return from_candid_opt_n82(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVentureGroup(arg0);
            return from_candid_opt_n82(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinVentureGroup(arg0: string): Promise<{
        userGroups: Array<string>;
        wasNewMember: boolean;
        group?: VentureGroup;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.joinVentureGroup(arg0);
                return from_candid_record_n83(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinVentureGroup(arg0);
            return from_candid_record_n83(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordPayout(arg0: string, arg1: Principal, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPayout(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPayout(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n84(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n84(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitRSVP(arg0: string, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRSVP(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRSVP(arg0, arg1, arg2);
            return result;
        }
    }
    async updateContribution(arg0: string, arg1: Contribution): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContribution(arg0, to_candid_Contribution_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContribution(arg0, to_candid_Contribution_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMilestoneStatus(arg0: string, arg1: MilestoneStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMilestoneStatus(arg0, to_candid_MilestoneStatus_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMilestoneStatus(arg0, to_candid_MilestoneStatus_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePlannedPayment(arg0: string, arg1: PlannedPayment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlannedPayment(arg0, to_candid_PlannedPayment_n25(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlannedPayment(arg0, to_candid_PlannedPayment_n25(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateVentureGroup(arg0: string, arg1: VentureGroup): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVentureGroup(arg0, to_candid_VentureGroup_n29(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVentureGroup(arg0, to_candid_VentureGroup_n29(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadMilestoneImage(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadMilestoneImage(arg0, await to_candid_ExternalBlob_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadMilestoneImage(arg0, await to_candid_ExternalBlob_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadReceiptImage(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadReceiptImage(arg0, await to_candid_ExternalBlob_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadReceiptImage(arg0, await to_candid_ExternalBlob_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ActivityType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityType): ActivityType {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Activity_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Activity): Activity {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_ContributionCycle_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContributionCycle): ContributionCycle {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_ContributionStatus_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContributionStatus): ContributionStatus {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_ContributionWithProfile_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContributionWithProfile): ContributionWithProfile {
    return from_candid_record_n63(_uploadFile, _downloadFile, value);
}
function from_candid_Contribution_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Contribution): Contribution {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
async function from_candid_Expense_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expense): Promise<Expense> {
    return await from_candid_record_n66(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_GroupDashboardData_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GroupDashboardData): Promise<GroupDashboardData> {
    return await from_candid_record_n70(_uploadFile, _downloadFile, value);
}
function from_candid_GroupMember_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GroupMember): GroupMember {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_MilestoneStatus_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MilestoneStatus): MilestoneStatus {
    return from_candid_variant_n75(_uploadFile, _downloadFile, value);
}
async function from_candid_Milestone_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Milestone): Promise<Milestone> {
    return await from_candid_record_n73(_uploadFile, _downloadFile, value);
}
function from_candid_PlannedPaymentStatus_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlannedPaymentStatus): PlannedPaymentStatus {
    return from_candid_variant_n81(_uploadFile, _downloadFile, value);
}
function from_candid_PlannedPayment_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlannedPayment): PlannedPayment {
    return from_candid_record_n79(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_VentureGroup_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VentureGroup): VentureGroup {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n52(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n68(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GroupProgress]): GroupProgress | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VentureGroup]): VentureGroup | null {
    return value.length === 0 ? null : from_candid_VentureGroup_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    activityType: _ActivityType;
    groupId: string;
    timestamp: _Time;
    details: string;
}): {
    id: string;
    activityType: ActivityType;
    groupId: string;
    timestamp: Time;
    details: string;
} {
    return {
        id: value.id,
        activityType: from_candid_ActivityType_n39(_uploadFile, _downloadFile, value.activityType),
        groupId: value.groupId,
        timestamp: value.timestamp,
        details: value.details
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    members: Array<_GroupMember>;
    admin: Principal;
    endDate: _Time;
    name: string;
    description: string;
    contributionCycle: _ContributionCycle;
    targetAmount: bigint;
    currency: string;
    category: string;
    monthlyContributionAmount: bigint;
    startDate: _Time;
}): {
    id: string;
    members: Array<GroupMember>;
    admin: Principal;
    endDate: Time;
    name: string;
    description: string;
    contributionCycle: ContributionCycle;
    targetAmount: bigint;
    currency: string;
    category: string;
    monthlyContributionAmount: bigint;
    startDate: Time;
} {
    return {
        id: value.id,
        members: from_candid_vec_n44(_uploadFile, _downloadFile, value.members),
        admin: value.admin,
        endDate: value.endDate,
        name: value.name,
        description: value.description,
        contributionCycle: from_candid_ContributionCycle_n49(_uploadFile, _downloadFile, value.contributionCycle),
        targetAmount: value.targetAmount,
        currency: value.currency,
        category: value.category,
        monthlyContributionAmount: value.monthlyContributionAmount,
        startDate: value.startDate
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    role: _UserRole;
    joinedDate: _Time;
}): {
    principal: Principal;
    role: UserRole;
    joinedDate: Time;
} {
    return {
        principal: value.principal,
        role: from_candid_UserRole_n47(_uploadFile, _downloadFile, value.role),
        joinedDate: value.joinedDate
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    created: _Time;
    country: string;
    name: string;
    role: _UserRole;
    phone: [] | [string];
}): {
    created: Time;
    country: string;
    name: string;
    role: UserRole;
    phone?: string;
} {
    return {
        created: value.created,
        country: value.country,
        name: value.name,
        role: from_candid_UserRole_n47(_uploadFile, _downloadFile, value.role),
        phone: record_opt_to_undefined(from_candid_opt_n54(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    member: Principal;
    status: _ContributionStatus;
    groupId: string;
    amount: bigint;
    datePaid: [] | [_Time];
}): {
    id: string;
    member: Principal;
    status: ContributionStatus;
    groupId: string;
    amount: bigint;
    datePaid?: Time;
} {
    return {
        id: value.id,
        member: value.member,
        status: from_candid_ContributionStatus_n58(_uploadFile, _downloadFile, value.status),
        groupId: value.groupId,
        amount: value.amount,
        datePaid: record_opt_to_undefined(from_candid_opt_n60(_uploadFile, _downloadFile, value.datePaid))
    };
}
function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    contributorName: string;
    member: Principal;
    status: _ContributionStatus;
    groupId: string;
    amount: bigint;
    datePaid: [] | [_Time];
}): {
    id: string;
    contributorName: string;
    member: Principal;
    status: ContributionStatus;
    groupId: string;
    amount: bigint;
    datePaid?: Time;
} {
    return {
        id: value.id,
        contributorName: value.contributorName,
        member: value.member,
        status: from_candid_ContributionStatus_n58(_uploadFile, _downloadFile, value.status),
        groupId: value.groupId,
        amount: value.amount,
        datePaid: record_opt_to_undefined(from_candid_opt_n60(_uploadFile, _downloadFile, value.datePaid))
    };
}
async function from_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    receiptImage: [] | [_ExternalBlob];
    description: string;
    dateSpent: _Time;
    groupId: string;
    addedBy: Principal;
    category: string;
    amount: bigint;
}): Promise<{
    id: string;
    receiptImage?: ExternalBlob;
    description: string;
    dateSpent: Time;
    groupId: string;
    addedBy: Principal;
    category: string;
    amount: bigint;
}> {
    return {
        id: value.id,
        receiptImage: record_opt_to_undefined(await from_candid_opt_n67(_uploadFile, _downloadFile, value.receiptImage)),
        description: value.description,
        dateSpent: value.dateSpent,
        groupId: value.groupId,
        addedBy: value.addedBy,
        category: value.category,
        amount: value.amount
    };
}
async function from_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activityFeed: Array<_Activity>;
    recentContributions: Array<_ContributionWithProfile>;
    groupId: string;
    groupProgress: _GroupProgress;
    groupInfo: _VentureGroup;
    financialSummary: _FinancialSummary;
    milestones: Array<_Milestone>;
}): Promise<{
    activityFeed: Array<Activity>;
    recentContributions: Array<ContributionWithProfile>;
    groupId: string;
    groupProgress: GroupProgress;
    groupInfo: VentureGroup;
    financialSummary: FinancialSummary;
    milestones: Array<Milestone>;
}> {
    return {
        activityFeed: from_candid_vec_n36(_uploadFile, _downloadFile, value.activityFeed),
        recentContributions: from_candid_vec_n61(_uploadFile, _downloadFile, value.recentContributions),
        groupId: value.groupId,
        groupProgress: value.groupProgress,
        groupInfo: from_candid_VentureGroup_n42(_uploadFile, _downloadFile, value.groupInfo),
        financialSummary: value.financialSummary,
        milestones: await from_candid_vec_n71(_uploadFile, _downloadFile, value.milestones)
    };
}
async function from_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _MilestoneStatus;
    name: string;
    description: string;
    groupId: string;
    targetDate: _Time;
    image: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    status: MilestoneStatus;
    name: string;
    description: string;
    groupId: string;
    targetDate: Time;
    image?: ExternalBlob;
}> {
    return {
        id: value.id,
        status: from_candid_MilestoneStatus_n74(_uploadFile, _downloadFile, value.status),
        name: value.name,
        description: value.description,
        groupId: value.groupId,
        targetDate: value.targetDate,
        image: record_opt_to_undefined(await from_candid_opt_n67(_uploadFile, _downloadFile, value.image))
    };
}
function from_candid_record_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    member: Principal;
    status: _PlannedPaymentStatus;
    dueDate: _Time;
    description: string;
    groupId: string;
    amount: bigint;
}): {
    id: string;
    member: Principal;
    status: PlannedPaymentStatus;
    dueDate: Time;
    description: string;
    groupId: string;
    amount: bigint;
} {
    return {
        id: value.id,
        member: value.member,
        status: from_candid_PlannedPaymentStatus_n80(_uploadFile, _downloadFile, value.status),
        dueDate: value.dueDate,
        description: value.description,
        groupId: value.groupId,
        amount: value.amount
    };
}
function from_candid_record_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userGroups: Array<string>;
    wasNewMember: boolean;
    group: [] | [_VentureGroup];
}): {
    userGroups: Array<string>;
    wasNewMember: boolean;
    group?: VentureGroup;
} {
    return {
        userGroups: value.userGroups,
        wasNewMember: value.wasNewMember,
        group: record_opt_to_undefined(from_candid_opt_n82(_uploadFile, _downloadFile, value.group))
    };
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expenseAdded: null;
} | {
    memberJoined: null;
} | {
    milestoneUpdated: null;
} | {
    contributionMade: null;
}): ActivityType {
    return "expenseAdded" in value ? ActivityType.expenseAdded : "memberJoined" in value ? ActivityType.memberJoined : "milestoneUpdated" in value ? ActivityType.milestoneUpdated : "contributionMade" in value ? ActivityType.contributionMade : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    quarterly: null;
} | {
    monthly: null;
} | {
    weekly: null;
}): ContributionCycle {
    return "quarterly" in value ? ContributionCycle.quarterly : "monthly" in value ? ContributionCycle.monthly : "weekly" in value ? ContributionCycle.weekly : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    overdue: null;
}): ContributionStatus {
    return "pending" in value ? ContributionStatus.pending : "paid" in value ? ContributionStatus.paid : "overdue" in value ? ContributionStatus.overdue : value;
}
function from_candid_variant_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
}): MilestoneStatus {
    return "pending" in value ? MilestoneStatus.pending : "completed" in value ? MilestoneStatus.completed : value;
}
function from_candid_variant_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    paid: null;
} | {
    missed: null;
}): PlannedPaymentStatus {
    return "upcoming" in value ? PlannedPaymentStatus.upcoming : "paid" in value ? PlannedPaymentStatus.paid : "missed" in value ? PlannedPaymentStatus.missed : value;
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Activity>): Array<Activity> {
    return value.map((x)=>from_candid_Activity_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VentureGroup>): Array<VentureGroup> {
    return value.map((x)=>from_candid_VentureGroup_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GroupMember>): Array<GroupMember> {
    return value.map((x)=>from_candid_GroupMember_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Contribution>): Array<Contribution> {
    return value.map((x)=>from_candid_Contribution_n56(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContributionWithProfile>): Array<ContributionWithProfile> {
    return value.map((x)=>from_candid_ContributionWithProfile_n62(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expense>): Promise<Array<Expense>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Expense_n65(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Milestone>): Promise<Array<Milestone>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Milestone_n72(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlannedPayment>): Array<PlannedPayment> {
    return value.map((x)=>from_candid_PlannedPayment_n78(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): _ActivityType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Activity_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Activity): _Activity {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ContributionCycle_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContributionCycle): _ContributionCycle {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_ContributionStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContributionStatus): _ContributionStatus {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Contribution_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Contribution): _Contribution {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_Expense_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Expense): Promise<_Expense> {
    return await to_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_GroupMember_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GroupMember): _GroupMember {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_MilestoneStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MilestoneStatus): _MilestoneStatus {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function to_candid_Milestone_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Milestone): Promise<_Milestone> {
    return await to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_PlannedPaymentStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlannedPaymentStatus): _PlannedPaymentStatus {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_PlannedPayment_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlannedPayment): _PlannedPayment {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n85(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_VentureGroup_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VentureGroup): _VentureGroup {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    member: Principal;
    status: ContributionStatus;
    groupId: string;
    amount: bigint;
    datePaid?: Time;
}): {
    id: string;
    member: Principal;
    status: _ContributionStatus;
    groupId: string;
    amount: bigint;
    datePaid: [] | [_Time];
} {
    return {
        id: value.id,
        member: value.member,
        status: to_candid_ContributionStatus_n14(_uploadFile, _downloadFile, value.status),
        groupId: value.groupId,
        amount: value.amount,
        datePaid: value.datePaid ? candid_some(value.datePaid) : candid_none()
    };
}
async function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    receiptImage?: ExternalBlob;
    description: string;
    dateSpent: Time;
    groupId: string;
    addedBy: Principal;
    category: string;
    amount: bigint;
}): Promise<{
    id: string;
    receiptImage: [] | [_ExternalBlob];
    description: string;
    dateSpent: _Time;
    groupId: string;
    addedBy: Principal;
    category: string;
    amount: bigint;
}> {
    return {
        id: value.id,
        receiptImage: value.receiptImage ? candid_some(await to_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value.receiptImage)) : candid_none(),
        description: value.description,
        dateSpent: value.dateSpent,
        groupId: value.groupId,
        addedBy: value.addedBy,
        category: value.category,
        amount: value.amount
    };
}
async function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: MilestoneStatus;
    name: string;
    description: string;
    groupId: string;
    targetDate: Time;
    image?: ExternalBlob;
}): Promise<{
    id: string;
    status: _MilestoneStatus;
    name: string;
    description: string;
    groupId: string;
    targetDate: _Time;
    image: [] | [_ExternalBlob];
}> {
    return {
        id: value.id,
        status: to_candid_MilestoneStatus_n21(_uploadFile, _downloadFile, value.status),
        name: value.name,
        description: value.description,
        groupId: value.groupId,
        targetDate: value.targetDate,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value.image)) : candid_none()
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    member: Principal;
    status: PlannedPaymentStatus;
    dueDate: Time;
    description: string;
    groupId: string;
    amount: bigint;
}): {
    id: string;
    member: Principal;
    status: _PlannedPaymentStatus;
    dueDate: _Time;
    description: string;
    groupId: string;
    amount: bigint;
} {
    return {
        id: value.id,
        member: value.member,
        status: to_candid_PlannedPaymentStatus_n27(_uploadFile, _downloadFile, value.status),
        dueDate: value.dueDate,
        description: value.description,
        groupId: value.groupId,
        amount: value.amount
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    members: Array<GroupMember>;
    admin: Principal;
    endDate: Time;
    name: string;
    description: string;
    contributionCycle: ContributionCycle;
    targetAmount: bigint;
    currency: string;
    category: string;
    monthlyContributionAmount: bigint;
    startDate: Time;
}): {
    id: string;
    members: Array<_GroupMember>;
    admin: Principal;
    endDate: _Time;
    name: string;
    description: string;
    contributionCycle: _ContributionCycle;
    targetAmount: bigint;
    currency: string;
    category: string;
    monthlyContributionAmount: bigint;
    startDate: _Time;
} {
    return {
        id: value.id,
        members: to_candid_vec_n31(_uploadFile, _downloadFile, value.members),
        admin: value.admin,
        endDate: value.endDate,
        name: value.name,
        description: value.description,
        contributionCycle: to_candid_ContributionCycle_n34(_uploadFile, _downloadFile, value.contributionCycle),
        targetAmount: value.targetAmount,
        currency: value.currency,
        category: value.category,
        monthlyContributionAmount: value.monthlyContributionAmount,
        startDate: value.startDate
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    role: UserRole;
    joinedDate: Time;
}): {
    principal: Principal;
    role: _UserRole;
    joinedDate: _Time;
} {
    return {
        principal: value.principal,
        role: to_candid_UserRole_n23(_uploadFile, _downloadFile, value.role),
        joinedDate: value.joinedDate
    };
}
function to_candid_record_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    created: Time;
    country: string;
    name: string;
    role: UserRole;
    phone?: string;
}): {
    created: _Time;
    country: string;
    name: string;
    role: _UserRole;
    phone: [] | [string];
} {
    return {
        created: value.created,
        country: value.country,
        name: value.name,
        role: to_candid_UserRole_n23(_uploadFile, _downloadFile, value.role),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    activityType: ActivityType;
    groupId: string;
    timestamp: Time;
    details: string;
}): {
    id: string;
    activityType: _ActivityType;
    groupId: string;
    timestamp: _Time;
    details: string;
} {
    return {
        id: value.id,
        activityType: to_candid_ActivityType_n10(_uploadFile, _downloadFile, value.activityType),
        groupId: value.groupId,
        timestamp: value.timestamp,
        details: value.details
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): {
    expenseAdded: null;
} | {
    memberJoined: null;
} | {
    milestoneUpdated: null;
} | {
    contributionMade: null;
} {
    return value == ActivityType.expenseAdded ? {
        expenseAdded: null
    } : value == ActivityType.memberJoined ? {
        memberJoined: null
    } : value == ActivityType.milestoneUpdated ? {
        milestoneUpdated: null
    } : value == ActivityType.contributionMade ? {
        contributionMade: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContributionStatus): {
    pending: null;
} | {
    paid: null;
} | {
    overdue: null;
} {
    return value == ContributionStatus.pending ? {
        pending: null
    } : value == ContributionStatus.paid ? {
        paid: null
    } : value == ContributionStatus.overdue ? {
        overdue: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MilestoneStatus): {
    pending: null;
} | {
    completed: null;
} {
    return value == MilestoneStatus.pending ? {
        pending: null
    } : value == MilestoneStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlannedPaymentStatus): {
    upcoming: null;
} | {
    paid: null;
} | {
    missed: null;
} {
    return value == PlannedPaymentStatus.upcoming ? {
        upcoming: null
    } : value == PlannedPaymentStatus.paid ? {
        paid: null
    } : value == PlannedPaymentStatus.missed ? {
        missed: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContributionCycle): {
    quarterly: null;
} | {
    monthly: null;
} | {
    weekly: null;
} {
    return value == ContributionCycle.quarterly ? {
        quarterly: null
    } : value == ContributionCycle.monthly ? {
        monthly: null
    } : value == ContributionCycle.weekly ? {
        weekly: null
    } : value;
}
function to_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<GroupMember>): Array<_GroupMember> {
    return value.map((x)=>to_candid_GroupMember_n32(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
